apiVersion: v1
kind: Pod
spec:
  containers:
  - name: class-run-pod
    image: docker:20.10.7
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  initContainers:
  - name: install-git
    image: alpine:3.12
    command:
    - sh
    - -c
    - apk add --no-cache git
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
#