pipeline {
    agent {
        kubernetes {
            label 'class-run-pod'
            yamlFile 'Lab 1 - Files/build-pod.yaml'
            defaultContainer 'class-run-pod'
            namespace 'ci'
        }
    }

    environment {
        GITHUB_URL = 'https://github.com/TheBlueDrara/class-lab.git'
        IMAGE_NAME = 'thebluedrara/devops-class'
        GITHUB_CREDENTIALS_ID = 'github-cred'
        DOCKER_HUB_CREDENTIALS_ID = 'docker-cred'
        GITHUB_API_URL = 'https://api.github.com/repos/TheBlueDrara/class-lab/pulls'
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Checking out code from ${GITHUB_URL}"
                git url: "${GITHUB_URL}", credentialsId: "${GITHUB_CREDENTIALS_ID}"
            }
        }

        stage('Build Image') {
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_NAME}:${env.BRANCH_NAME}-${env.BUILD_ID}", "--no-cache .")
                }
            }
        }

        stage('Create Pull Request') {
            when {
                not {
                    branch 'main'
                }
            }
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github-cred', usernameVariable: 'GITHUB_USERNAME', passwordVariable: 'GITHUB_TOKEN')]) {
                        sh """
                        curl -s --header "Authorization: token ${GITHUB_TOKEN}" -X POST "${GITHUB_API_URL}" \
                        --data '{
                            "title": "PR from ${env.BRANCH_NAME} into main",
                            "head": "${env.BRANCH_NAME}",
                            "base": "main",
                            "body": "Automatically generated PR",
                            "maintainer_can_modify": true
                        }'
                        """
                    }
                }
            }
        }

        stage('Push Docker Image') {
            when {
                branch 'main'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-cred') {
                        dockerImage.push("latest")
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                node {
                    container('class-run-pod') {
                        cleanWs()
                    }
                }
            }
        }
    }
}
