pipeline {
    agent any

    environment {
        GITHUB_URL = 'https://github.com/TheBlueDrara/class-lab.git'
        IMAGE_NAME = 'thebluedrara/devops-class'
        GITHUB_CREDENTIALS_ID = 'github-cred'
        DOCKER_HUB_CREDENTIALS_ID = 'docker-cred'
    }

    stages {
        stage('Checkout Code') {
            steps {
                echo "Checking out code from ${GITHUB_URL}"
                git url: "${GITHUB_URL}", credentialsId: "${GITHUB_CREDENTIALS_ID}"
            }
        }

        stage('Build Image') {
            steps {
                script {
                    dockerImage = docker.build("${IMAGE_NAME}:${env.BRANCH_NAME}-${env.BUILD_ID}", "--no-cache .")
                }
            }
        }

        stage('Push Docker Image') {
            when {
                branch 'main'
            }
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-cred') {
                        dockerImage.push("latest")
                    }
                }
            }
        }
    }

    post {
        always {
            script {
                cleanWs()
            }
        }
    }
}
