apiVersion: v1
kind: Pod
spec:
  containers:
  - name: class-run-pod
    image: docker:20.10.7
    command:
    - cat
    tty: true
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock



#DEPLOY JENKINS, CREATE A MULTIBRANCH PIPELINE, ADD CREDENTIALS, AND SEE IF IT WORKS